version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5-jessie-browsers
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -U pip setuptools
            pip install .[dev]
      - run:
          name: 'run tests'
          command: |
            source venv/bin/activate
            python -m unittest
